init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"

install:
  - ps: New-Item .\new_empty_file.txt -type file

build_script:

deploy_script:
  - appveyor PushArtifact .\new_empty_file.txt
