init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"

install:
  - ps: New-Item .\new_empty_file.txt -type file

build_script:
  - ps: Write-Host "build_script" -ForegroundColor Magenta

test_script:
  - ps: Write-Host "test_script" -ForegroundColor Magenta

deploy_script:
  - ps: Get-Date
  - appveyor PushArtifact .\new_empty_file.txt
  - ps: Get-Date
